### ISSUE TITLE
Got SyntaxError

### ISSUE THREAD

**Issue by victord15** [georg95/hamster-bike-keygen#1]
Hi
After starting script i got this message:
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

Whats wrong?
![Screenshot_20240730-045848_Firefox](https://github.com/user-attachments/assets/9ed0e5dc-2e7a-4b34-94e7-232d8fb0fbcd)

**Comment by georg95** [comment]
Error from server, now it should be displayed https://github.com/georg95/hamster-bike-keygen/commit/9aa6b223605287695b20f1d80dde4f96f17442cb
