### ISSUE TITLE
No bike icon on the page

### ISSUE THREAD

**Issue by victord15** [georg95/hamster-bike-keygen#2]
Hi
No bike icon on the example.com page.
Why?

![Screenshot_20240730-073557_Firefox](https://github.com/user-attachments/assets/48fcf331-c32b-429e-a80d-1ef19eafc02e)

**Comment by georg95** [comment]
sorry, updated a lot. It'll show here:
https://georg95.github.io/bike-keygen.html

**Comment by victord15** [comment]
Yes, it's working!
Thank you!!!
