### ISSUE TITLE
gives the same code

### ISSUE THREAD

**Issue by ontwol4rrr** [georg95/hamster-bike-keygen#3]
I press it, it reaches 33 percent and gives the same code. help me solve the problem please

**Comment by georg95** [comment]
Activate this code to get next one.

Thats exactly how it is in the game. It's to avoid possible ban in future.

**Comment by jeremyshainberg** [comment]
At first, thank you for your great work.
I have a problem. It doesn't work after 3 or 4 codes (after 3 or 4 codes, on 80% it jumps to 70% and it doesn't give any code at the end)

**Comment by QasxcTc** [comment]
BIKE-31S-E25D-026N-GB5
