### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by BablGUM** [georg95/hamster-bike-keygen#4]
I run your script through google, but nothing appears or changes

**Comment by Smile22-nc** [comment]
The script is infinitely reinstalled
![Screenshot_50](https://github.com/user-attachments/assets/240493d9-efb6-4057-8646-2b8a7a81f042)
![Screenshot_51](https://github.com/user-attachments/assets/5fb0073d-bdb1-4bed-ba37-ed90b173bfb8)
